<?php
//tables
//customers
$Customer ="CREATE TABLE Customers
(id INT(6)UNSIGNED AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
second_name VARCHAR(30) NOT NULL,
phone_no VARCHAR(10) NOT NULL,
pasword VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIME ON UPDATE CURRENT_TIMESTAMP";
//admin
$admin = "CREATE TABLE Admin_user
(id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
second_name VARCHAR(30) NOT NULL,
phone_no VARCHAR(30) NOT NULL,
email VARCHAR(50) NOT NULL,
password VARCHAR(50),
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)";
//products
$Products = "CREATE TABLE Products(
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(20) NOT NULL,
comany INT(6) NOT NULL,
publish_year YEAR,
price FLOAT(10) NOT NULL,
stock INT(100) NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)";
//Company
$Company = "CREATE TABLE Authors(
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
second_name VARCHAR(30) NOT NULL,
bio VARCHAR(255))";
//order items
$Order_items = "CREATE TABLE Order_items(
id INT(6) UNSIGNED  AUTO_INCREMENT PRIMARY KEY,
order_id INT (6),
product_id INT(6),
price FLOAT(10),
quantity INT(100))";
 //orders   
$Orders = "CREATE TABLE Orders (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
customer_id INT(6) NOT NULL,
total_amount FLOAT(6) NOT NULL,
status VARCHAR(20) NOT NULL,
delivery_status VARCHAR(20)
)";
//category
$Category = "CREATE TABLE Category(
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(20) NOT NULL,
description VARCHAR(255) NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)";


?>